CATEGORIAS = [
    "Gestion de proyectos", "Desarrollo de Software", "Ciencia de datos", "Operaciones", "Operaciones de TI",
    "Seguridad de la información", "Inteligencia artificial", "Redes y telecomunicaciones", "Sistemas de información", "Operaciones de red",
]

DIGITOS_VERIFICADORES = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K']

DOMINIOS = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'live.com', 'icloud.com', 'zoho.com', 'protonmail.com', 'tutanota.com', 'yandex.com']

TITULO_INICIO = [
    "Cómo", "Cuándo", "Dónde", "Por qué", "Objetivos de", "Operar y",
]
TITULO_VERBOS = [
    "aprender", "usar", "crear", "mejorar", "entender", "desarrollar"
]
TITULO_OBJETOS = [
    "Software en Python", "bases de datos", "IA en Software", "algoritmos", "aplicaciones web", "seguridad informática",
    "redes neuronales", "machine learning", "Gestion de big data", "cloud computing", "programación funcional", "Gestion en POO",
    "Software y Hardware", "internet de las cosas", "blockchain"
]

NOMBRES = [
    'Juan Joaquín Ramírez Ruiz',
    'José Saldivia Cartes',
    'Juan Morales Muñoz',
    'María Ojeda',
    'Carolina Flores Pérez',
    'Rosa Tatiana Vidal Contreras',
    'Josefina Gallardo Santander',
    'Ana Díaz Zúñiga',
    'Marcela Roa',
    'Elsa Román Becerra',
    'Gladys Medina',
    'Juan José Peña Pereira',
    'Irma Carmen Farías Rivera',
    'Matías Pedro Gómez Jiménez',
    'Camila Saavedra',
    'Eugenio Barra Avendaño',
    'William Nelson Ibáñez Rubio',
    'Joselyn Catalina Espinoza Mardones',
    'Lía Alicia Morales Muñoz',
    'Eleazar Pérez Sáez',
    'Florencio Pablo Ramírez Aguilar',
    'Cristobal Alexis Sánchez Ahumada',
    'David Diego Aguirre Carrasco',
    'Luis Vera',
    'María Ana Tapia Castro',
    'María Peralta Lara',
    'Adrián Diego González Morales',
    'Georgina Natali Aguayo Fernández',
    'Elba Patricia Aguilera Gallardo',
    'Bernardo Carlos Martínez Fica',
    'Rosa Arancibia-Cancino Pino',
    'Juan Castillo Calderón',
    'Pía Jara Letelier',
    'Benjamín Miguel Solís Rojas',
    'José López Cisterna',
    'Junior Renato Campos Morales',
    'Cristian Juan Durán Vásquez',
    'María Mónica Sáez González',
    'Geraldine Isabel Soto Salas',
    'Miguel Darwin Urbina Castro',
    'Leopoldo Pedro Avendaño Cárdenas',
    'Juan Eric Vásquez González',
    'Teresa Viviana Zamorano Rojas',
    'Camilo Luis González Garrido',
    'Erica Olmos-Martínez',
    'Juana Contreras Barrera',
    'Christian Gabriel Bravo Valdés',
    'Antonia Graciela Guerra Núñez',
    'Emilio Miguel Becerra Abarca',
    'Matías Lagos-Carreño Pizarro',
    'Luciano Héctor Véliz Miranda',
    'Gladys Soto',
    'Freddy Jaime Zambrano García',
    'Sonia Muñoz Sáez',
    'Liam Sepúlveda',
    'Andrea Lagos Astorga',
    'Jorge Ángel Cuevas Guerra',
    'Luis Jorge Soto Sepúlveda',
    'Nora Michelle Acevedo San Martín',
    'Ruth Jiménez Ramos',
    'Violeta Rodríguez',
    'Camila Fabiola Alvarado Sepúlveda',
    'Montserrat Lizana',
    'Juan Sebastián Gálvez Mondaca',
    'Patricia Marcelina Cancino Matamala',
    'María Javiera Luna Tapia',
    'Francisco Martínez Gaete',
    'Verónica Villagrán',
    'Humberto Gutiérrez Contreras',
    'Roberto Figueroa',
    'Jenny Orfelina Cisternas Ortega',
    'Juan Sebastián Carrasco Pérez',
    'Ruth Yolanda Silva Garrido',
    'Iván Daniel San Martín Leal',
    'José Venegas Mora',
    'Camilo Jonatan Tapia Araneda',
    'Isidora Lizama',
    'Ana Bravo-Figueroa',
    'María Cecilia Díaz Ibarra',
    'Antonieta Antonia Herrera Méndez',
    'Bastián Luis Leiva Zúñiga',
    'Jaime Pedro Fonseca Miranda',
    'Marcelo Villagrán',
    'Noemí Catherine Maldonado Robles',
    'Felipe Morales Vivanco',
    'Berta Sabina Chávez Blanco',
    'Carmen Isabel Ortega Vásquez',
    'Cecilia Cornejo Ávila',
    'Guillermo Gutiérrez',
    'Jacqueline Ana Neira Gajardo',
    'Sebastián Arturo Oñate Figueroa',
    'Fernando Maximiliano Muñoz Rivera',
    'María Orellana',
    'Verónica Meza Becerra',
    'Aurora Beatriz Aguilar Cerda',
    'María Rosa Araneda Ortiz',
    'Constanza María Suárez Venegas',
    'Andrea Ruiz Ortiz',
    'Carlos Castro',
    'Arturo Albornoz Díaz',
    'Mateo Ojeda Durán',
    'Krishna Carolina Duarte Briones',
    'Carlos Morales',
    'Flor María Ortiz Villagrán',
    'Evelyn Gutiérrez',
    'Yohan Quiroz Salgado',
    'Diana Maite Castillo Urbina',
    'Víctor José González Fernández',
    'Olga Noelia Lara Barraza',
    'Jorge Sergio Riquelme Jiménez',
    'Gloria Soledad Pineda González',
    'Ana Oñate Lorca',
    'Rebeca Guerrero',
    'María Isolina Carrasco Silva',
    'Domingo Fabio López Ortiz',
    'Patricio Díaz Fuentealba',
    'Ismael Juan Sandoval Tello',
    'Santiago Sebastián Carrillo Ríos',
    'Cynthia Alejandra Salinas Torres',
    'José Luis Torres Vera',
    'Antonia Silvana Inostroza González',
    'Benjamín Esteban Araya Fuentealba',
    'Inés Olmos Miranda',
    'Emma Myriam Lizana Tobar',
    'Eduardo Patricio Díaz Mejías',
    'Paz Saavedra Ríos',
    'Alejandro Espinoza López',
    'Yesica Antonia González Pino',
    'Isidora Jeanette Orellana Castillo',
    'Nicole Isidora Osorio Rojas',
    'Fabián Hernández',
    'Alex Torres Parra',
    'Camila Julieta Jara Abarca',
    'Manuela Margarita Barría Espinoza',
    'María González',
    'Aída Alexandra Ojeda Donoso',
    'Esteban Raúl Cisternas Barraza',
    'Noelia Valenzuela Norambuena',
    'Félix Manríquez',
    'Alejandro Luis Martínez Villegas',
    'Diana Contreras',
    'María Carolina Valdebenito Vera',
    'Yolanda Ana Rojas Pozo',
    'Fernanda Adriana Berríos González',
    'Patricia Quezada',
    'Carlos Ariel Robles Ayala',
    'Francis Karla Almonacid Aguayo',
    'Berta Rodríguez',
    'Jeannette Julieta Opazo Hidalgo',
    'Sofía Daniela Soto Castillo',
    'Marcelo Lobos',
    'Irma Rosalía Arroyo Arancibia',
    'Patricia Cintia Morales Salinas',
    'Gonzalo Gatica',
    'Herminda Daniela Valdivia Contreras',
    'Sofía Matilda Concha Vejar',
    'Franco Contreras Oyarzún',
    'Ximena Castillo González',
    'María Mery Rojas Rojas',
    'Mercedes Ana Pizarro Muñoz',
    'Dina Riquelme Concha',
    'Mariela Verdugo Bustos',
    'Ingrid Araya Arredondo',
    'Noelia Abarca Velásquez',
    'Florencia Paola Chávez Flores',
    'Carlos Godoy Gutiérrez',
    'Cristhian Roberto Álvarez Bravo',
    'Edith Madrid',
    'Edgardo Miguel González Ortiz',
    'Camila Rivas-Gutiérrez Román',
    'Dina Amy Vargas Rivera',
    'Aurora Rodríguez',
    'Francisca Inostroza Leal',
    'Daniela Claudia Pincheira Garrido',
    'Ada Dayana Silva Lara',
    'Antonio Luis Barría-Díaz Cortés',
    'Dominga Manríquez Morales',
    'Enrique Felipe Tapia Morales',
    'María Cabrera Sepúlveda',
    'Katherine Bárbara Araya Sepúlveda',
    'Eduardo Mella Fredes',
    'Máximo Jaime Bustos Fuenzalida',
    'Laura Javiera Tello Torres',
    'Gabriel Sebastián Verdugo Díaz',
    'Alexander Pedro Jara Yáñez',
    'Tamara Ema Vega Aguilera',
    'Christian Espinoza',
    'Carlos Díaz',
    'Guillermo Joel Mora Garay',
    'Rubén Díaz',
    'Sara Darling Acevedo Mejías',
    'Benito Jonathan Vargas Valderrama',
    'Luisa Valentina Labra Rojas',
    'Noelia Sandoval Barraza',
    'Marcos Tomás Araya Riquelme',
    'Fernanda Eliana Álvarez Palma',
    'Luis Vargas Díaz',
    'Isaac Pedro Cerda González',
    'Patricio Becerra Muñoz',
    'Rodolfo Allende',
    'Martina María Blanco Bravo',
    'Felipe Mario González Ahumada',
    'Amanda Pamela Toloza Robles',
    'Nicole María Ampuero Navarro',
    'Ana Stephanie Araya Henríquez',
    'María Johana Pinto González',
    'Abel Gabriel Solar Contreras',
    'Daniel Guillermo Ruiz Moreno',
    'Ester Jacqueline Gutiérrez Quinteros',
    'Peter Luis Hidalgo Muñoz',
    'Antonia Bárbara Olivares Zavala',
    'José Carrasco Arias',
    'Isabel Ramírez',
    'Bernardo Silva Araya',
    'Vicente Daniel Ortega Fernández',
    'Mauricio Iván Núñez Delgado',
    'Joaquín Fica',
    'Manuel Tapia',
    'Jorge Carlos Barros Carrasco',
    'Marjorie Norma Díaz Sepúlveda',
    'Rosa González Duarte',
    'Gloria San Martín',
    'Viviana Mariela Droguett Gutiérrez',
    'Erika Herrera Muñoz',
    'María Aguilar',
    'Vanessa Bárbara Cifuentes Inostroza',
    'David José Mancilla Rubio',
    'Aída Cuevas-Rodríguez Mora',
    'Joshua Luis Astudillo Ávalos',
    'Bernarda Florentina Catalán Norambuena',
    'Ramón Raúl Cárcamo Álvarez',
    'Bastián Sebastián Bórquez Miranda',
    'Eduardo Valenzuela',
    'Isabel Gladys Aguirre Cornejo',
    'Fernanda Flor Chacón Rubio',
    'Diego Alvarado',
    'Patricia Erika Zúñiga Aravena',
    'Boris Urzúa Ramírez',
    'Manuel Espinoza',
    'Viviana Muñoz Olivares',
    'Francisco Aníbal Muñoz Arce',
    'María Susan Catalán Blanco',
    'Juana María Molina Sepúlveda',
    'Aracely Jenny Echeverría Collao',
    'Marcela Claudia Pincheira Miranda',
    'Oscar Mancilla Pavez',
    'María Teresa Salinas Zúñiga',
    'Antonio Marcelo Hernández Rivera',
    'Sebastián Valenzuela Leiva',
    'Julio Javier Rivas Riffo',
    'Carlos Soto',
    'Violeta Maite Godoy Aguilera',
    'Josefina Marcela Olivares Campos',
    'Manuel Rodrigo Maldonado Gutiérrez',
    'Andrés Córdova Maturana',
    'Elizabeth Muñoz Rojas',
    'Patricia Kelly Soto Órdenes',
    'Joselyn Javiera Zúñiga Meneses',
    'Carolina Bárbara Agurto Toro',
    'Carmen Maricela Novoa Ramírez',
    'Carolina Astudillo Molina',
    'José Martínez Contreras',
    'David García Miranda',
    'Félix Navarro',
    'Elizabeth Susana Aguirre Henríquez',
    'Marcos Mariano Cares Donoso',
    'Erika Rosa Mena Fernández',
    'Monserrat Serrano',
    'Valeria Pereira Manríquez',
    'Silvia Ana Lillo Cornejo',
    'Ana Ximena Torres Guzmán',
    'Roxana Tamara Muñoz Avilés',
    'Alex Uribe Lizama',
    'Alicia María Avilés Rebolledo',
    'Juan Villagra Ponce',
    'Jorge Parra Pacheco',
    'Cinthia Bustos',
    'José Alonso Morales Ramírez',
    'Ángela Graciela Águila Letelier',
    'Mauricio Matías Cabrera Baeza',
    'Laura Francisca Rosales Chacón',
    'Ximena Jeanette Salazar Cancino',
    'Sebastián Juan Delgado Zamorano',
    'Edelmira Celis Pincheira',
    'Axel César Araya Vera',
    'Maite Ayala-Lobos Aguayo',
    'Antonella Valentina Hernández Aguilera',
    'Mauricio Torres',
    'Ema Ángela Ríos Contreras',
    'Verónica Muñoz Saavedra',
    'María Antonia Lorca Correa',
    'Geraldine Pulgar Cabezas',
    'Joel Francisco Troncoso Henríquez',
    'Santiago Abdón Parra Sáez',
    'Bárbara Valdés Bravo',
    'Lidia Karina Poblete Zamorano',
    'Anahí Silvia Loyola González',
    'Juan Isaac Rodríguez Ortega',
    'Martín Washington Flores Rivera',
    'Abelardo Peñaloza',
]

RESUMENES = [
    '''Doloribus aspernatur veniam sed vel molestias ad debitis. Quo numquam beatae itaque molestias perferendis earum.''',
    '''Accusamus voluptas quae molestias sapiente ex. Dolores consectetur reiciendis voluptates fugiat possimus sint.
Inventore eveniet consequatur.''',
    '''Eius atque aut iure. Deserunt consequuntur ullam facere. Nostrum architecto facere voluptatem.
Ad ex aliquam consequatur. Vero optio dolorem.''',
    '''Omnis vitae possimus voluptatem. Minima similique rem praesentium. Vitae quasi nam quisquam in dolorum hic.
Praesentium aperiam animi.''',
    '''Corrupti repellendus aliquid voluptate animi voluptates rerum. Repellendus est accusantium voluptas optio.''',
    '''Quidem tenetur consequuntur at nisi error natus excepturi. Ratione est accusamus numquam optio delectus. Distinctio quae et.''',
    '''Nisi alias minima debitis debitis. Debitis minima nobis quia repellendus nesciunt harum id. Doloribus et facere ducimus libero.''',
    '''Corrupti illum nulla eum iusto nobis voluptatibus. Corrupti amet error placeat ut.''',
    '''Vel nesciunt quae dolorem quod. Blanditiis reiciendis perferendis eaque cumque eum.''',
    '''Dolor inventore eveniet dolorem nemo atque recusandae. Dolore quis necessitatibus consequatur.''',
    '''Perspiciatis incidunt nihil aspernatur vitae aspernatur perspiciatis atque. Similique ullam inventore atque placeat recusandae.''',
    '''Officiis minus ipsam iure reiciendis ad at. Iusto nam laborum quaerat dolores.''',
    '''Sunt nisi aliquid similique nulla.''',
    '''Suscipit quisquam nihil blanditiis libero suscipit deleniti neque. Quam cum dolores corporis. Non quasi repellendus asperiores voluptas velit.''',
    '''Illo repellat ad sapiente veniam. Aperiam ab rem possimus dicta.''',
    '''Sit libero fugit ex doloribus modi molestias. Provident eaque voluptas cum aperiam. Praesentium ratione ex voluptate eligendi nobis.''',
    '''Sit autem ex rerum eveniet ullam.''',
    '''Unde repellat aut ad blanditiis. Assumenda labore excepturi mollitia earum. Perspiciatis quis eos optio.''',
    '''Nemo similique optio explicabo at nulla deleniti molestiae. Vero minus quibusdam voluptate optio adipisci ullam.''',
    '''Accusantium dolorem dicta. Voluptatum quia inventore iste ad modi debitis. Earum sequi rem nostrum a.''',
    '''Iusto dicta cupiditate. Error cum asperiores nemo doloremque. Sint minima exercitationem nemo officia quaerat velit.''',
    '''Numquam nisi dolorum soluta rerum consectetur et.
Magnam similique molestiae expedita ipsum. Vero vel nobis expedita.''',
    '''Deleniti quia atque est excepturi vitae odio. Vero impedit laudantium eius voluptates quisquam.''',
    '''Sapiente ea veritatis numquam quaerat placeat libero. Sunt iusto praesentium veritatis.''',
    '''Nihil sunt placeat sequi maxime.
Dolorem facilis cum. Voluptatum perferendis nihil nemo. Iusto unde laboriosam deserunt quod. Sapiente sit a eum.''',
    '''Temporibus impedit cum ex maiores sed. Facilis incidunt nesciunt voluptates.''',
    '''Reprehenderit aliquam vitae deserunt odio quasi. Ipsa sit ex nobis placeat quisquam temporibus.''',
    '''Minima eum eligendi molestiae corporis voluptatem. Eos eveniet maiores earum quas repellendus sunt rerum.''',
    '''Cum facilis nulla voluptates. Quibusdam amet tenetur ex maxime. Iusto doloribus itaque perspiciatis accusantium cumque cumque.''',
    '''Nobis ex accusamus non. Facilis velit saepe. Blanditiis accusantium laborum eligendi quae corrupti.''',
    '''Assumenda tenetur doloribus officiis praesentium rem.
Aperiam porro iure. Corrupti laborum perspiciatis.''',
    '''Ipsa iure asperiores. Facilis quam libero non laborum optio.
Dolorem iusto nemo fugit. Odio sint ipsum debitis. Praesentium debitis laudantium.''',
    '''Neque quia explicabo. Blanditiis officiis reiciendis deserunt. Fugit eligendi assumenda vero libero.''',
    '''Quasi cumque amet odio iure.
Nostrum facilis hic. Tempora aut molestias a. In adipisci autem.''',
    '''Dolorum reprehenderit culpa. Ducimus praesentium sunt ratione totam dolorem dignissimos. Corporis ipsa impedit deleniti quia. Minus eum praesentium.''',
    '''Quasi veritatis explicabo fuga. Explicabo voluptatem corrupti provident deserunt.''',
    '''Accusantium odio repudiandae exercitationem quis. Cupiditate asperiores voluptates aliquid dolore vitae.''',
    '''Accusantium velit quae doloribus totam quia sapiente. Quasi sint magnam nisi.''',
    '''Vel nihil animi optio quia. Nesciunt fuga voluptate totam nostrum accusantium totam.''',
    '''Assumenda perspiciatis perspiciatis eaque reiciendis facilis. Amet quis incidunt quia aut voluptates. Magnam inventore eligendi laborum.''',
    '''Ullam quae id nihil beatae labore. Blanditiis in laborum nobis perferendis fuga.
Saepe quam rem repellat non nihil.''',
    '''Sunt natus molestias saepe optio. Sint ipsam perferendis vitae vero. Maxime officiis maiores natus neque doloribus repudiandae.''',
    '''Dignissimos laborum cumque ullam adipisci. Magnam voluptas itaque quos. Ut ea nam quaerat animi alias.''',
    '''Itaque molestias repellat distinctio occaecati tenetur quia nulla. Excepturi voluptatum iste.''',
    '''Sit nisi nobis debitis sit quia. Qui odio iste. Eius perferendis veniam magni adipisci minus.''',
    '''Officiis vel exercitationem consequatur suscipit. Quasi odit quaerat asperiores dolorum eos odit.''',
    '''Nobis sapiente veniam libero a eligendi explicabo unde. Eum doloribus dolorum labore.''',
    '''Quam aliquid voluptatem amet laborum atque quos. Ducimus officia voluptatibus dolor laborum quaerat.''',
    '''Vitae magnam error rerum. Consequuntur iure hic quidem corrupti rem.''',
    '''Sapiente numquam ab deleniti iste fugiat.''',
    '''Amet iste aliquam sed. Eius magnam atque beatae. Natus enim beatae earum rem.
Sint inventore cumque necessitatibus.''',
    '''Adipisci nostrum consectetur tenetur ut quas praesentium inventore.
Repellat nihil amet. Voluptas quos temporibus eligendi.''',
    '''Rem voluptatem assumenda quo optio alias laborum. Minima numquam adipisci. Est sunt modi ea debitis quos.''',
    '''Ab corporis corrupti illo alias.''',
    '''Quasi et aspernatur nisi facere eaque earum. Quos alias iste omnis nostrum optio. Veniam atque vel perferendis.''',
    '''Ipsum suscipit ratione dolor assumenda. Exercitationem saepe praesentium quos. Reiciendis omnis aspernatur expedita delectus.''',
    '''Consectetur sed velit praesentium consequatur. Totam architecto possimus illo in. Consequuntur fugiat numquam perferendis et.''',
    '''Distinctio esse velit est necessitatibus dolore beatae. Ratione nisi dolor. Tempore dolores atque numquam exercitationem.''',
    '''Soluta amet ullam aliquam. Dolore debitis sed repellat ipsum debitis temporibus. Quasi rerum nemo nisi eum inventore.''',
    '''Nesciunt possimus repellat dolorum quasi.''',
    '''Occaecati vero aliquid veniam quasi. Voluptatum ad voluptatum iste recusandae. Reiciendis incidunt quod ea quis harum dolores consectetur.''',
    '''Dicta molestias a quam voluptatum optio consectetur. Fugit ipsam odio dolor fuga quibusdam nobis. Veritatis neque quasi sint corrupti perferendis.''',
    '''Numquam adipisci accusantium officiis. Veniam vitae aliquid enim ab hic.
Excepturi incidunt sunt ipsa laborum dicta.''',
    '''Fugit cumque dolorem saepe est. Consectetur rerum illo mollitia consequuntur assumenda odio.''',
    '''Laborum unde provident laboriosam fuga facere alias. Eos fugiat voluptatibus culpa quam laudantium facere. Laudantium dolores facilis sint.''',
    '''Quisquam aliquam id delectus asperiores delectus consequuntur quae.''',
    '''Vero dolores magni non. Amet aut culpa molestias quis. Quam at vitae accusantium culpa.''',
    '''Ad cumque voluptatem provident quis quo soluta. Aliquid adipisci pariatur officia placeat porro tempore.''',
    '''Quidem placeat quia animi. Voluptatum maiores aperiam.
Officiis rerum dolorum.''',
    '''Fugit sunt odit tempore.
Et perspiciatis assumenda maxime. A rem cupiditate aliquam magni.''',
    '''Quis quo earum fuga neque architecto error sunt. Nisi fuga omnis deserunt.''',
    '''Ullam distinctio eum. Officiis ipsam molestiae praesentium veritatis.
Omnis nihil natus. Nesciunt molestiae quisquam. Temporibus illum eligendi.''',
    '''Eaque beatae cumque. Explicabo sequi deleniti aperiam vitae corporis. Exercitationem voluptatum ex dicta.''',
    '''Esse tenetur animi autem.''',
    '''Quia voluptate occaecati dolorem nihil impedit maxime. Necessitatibus recusandae dolores illo incidunt.''',
    '''Earum ex architecto sed maxime dolor. Corporis velit repellat adipisci. Est libero possimus aliquid dolore nulla harum.''',
    '''Ullam natus aliquam omnis eveniet necessitatibus animi. Architecto eaque praesentium. Amet minima saepe perspiciatis pariatur blanditiis cupiditate.''',
    '''Vel quis itaque alias veritatis alias commodi.''',
    '''Quibusdam molestiae consequatur temporibus adipisci. A placeat iure. Dolorum voluptates veritatis sapiente.''',
    '''Ipsa culpa qui officiis porro.
Magnam veritatis rerum mollitia commodi. Repellat ad aut ullam. Ducimus quod quos cumque.''',
    '''Ex tempore dolor temporibus odit. A rem numquam sapiente blanditiis vitae. Perferendis amet necessitatibus ex velit tenetur consectetur alias.''',
    '''Incidunt excepturi quisquam reprehenderit.
Doloremque ipsa quidem asperiores. Blanditiis veniam voluptate aperiam repudiandae expedita.''',
    '''Enim odio nam. Alias excepturi dicta esse nulla aliquid. Quisquam neque natus ipsa.''',
    '''Hic voluptatibus assumenda quod fuga deleniti iste. Necessitatibus officia maiores cum. Expedita enim dolorem distinctio.''',
    '''Accusamus iste omnis sequi. Modi qui eum. Dolores at velit blanditiis neque recusandae.''',
    '''Cupiditate aut porro quidem impedit. Expedita molestiae deleniti excepturi eos. Maiores veniam debitis dolorum dolorum voluptas illo.''',
    '''Odit aliquam neque consectetur omnis odio id. Ex aliquid culpa error eius modi labore.''',
    '''Quis officia quis iure facere similique. Consequatur facilis quisquam eius aut. Nesciunt modi corporis optio expedita vitae quisquam.''',
    '''Deleniti ipsum fugiat rem ipsum. Saepe id magnam.''',
    '''Ab voluptatibus inventore harum occaecati exercitationem necessitatibus. Cum sint earum eligendi id.''',
    '''Eius ipsam tempore repellat at tempora natus eius.''',
    '''Vel quos harum hic maxime quisquam. Temporibus ullam magni nostrum totam perferendis aliquam.''',
    '''Est debitis a. Doloremque vero ipsa ad doloremque nostrum. Dicta molestias atque repellendus voluptate iusto.''',
    '''Impedit dolores suscipit repellendus odio autem at. Unde laborum quasi. Veniam amet id ipsam.''',
    '''Id minima id ad minima quisquam quos. Fugiat commodi ad ut. Blanditiis unde consequatur cupiditate.''',
    '''Ea sequi minima sit eaque repellat reprehenderit.
Reprehenderit corporis optio incidunt ad minus. Similique sint cumque occaecati blanditiis sunt.''',
    '''Sit vero accusamus saepe incidunt atque nam. Itaque nobis assumenda nesciunt quia laboriosam enim.''',
    '''Reprehenderit sapiente nam. Eum hic suscipit aspernatur ex.
Maiores ipsum sequi quaerat reiciendis. Facilis debitis nulla voluptate provident.''',
    '''Provident quibusdam atque at numquam. Dolores accusamus asperiores minima recusandae tempora.''',
    '''Sint impedit sapiente. Repellat officiis numquam cupiditate.''',
]
